FROM node:22-bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

# Copy package.json and package-lock.json first (for caching)
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of your backend code
COPY . .

EXPOSE 5000
CMD ["npm", "start"]
