FROM cgr.dev/chainguard/node:latest-dev
WORKDIR /app

# Copy package.json and package-lock.json first (for caching)
COPY package*.json ./

# Install Node.js dependencies with lockfile fidelity.
RUN npm ci

# Copy the rest of your backend code
COPY . .

EXPOSE 5000
CMD ["npm", "start"]
