FROM node:18
WORKDIR /app

# Copy package.json and package-lock.json first (for caching)
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of your backend code
COPY . .

EXPOSE 5000
CMD ["npm", "start"]
